trigger:
- main

pool:
  vmImage: 'ubuntu-latest'


steps:

- task: VeracodeCommunityScaAdoExtension@1
  inputs:
    scanType: 'directory'
    scanTarget: '$(Build.SourcesDirectory)'
    minCVSS: '5'
    failBuild: true
  env:
    SRCCLR_API_TOKEN: $(SECRET)

# Step 1: Package Binaries
- task: CmdLine@2
  displayName: Package Artifacts
  inputs:
    script: |
      curl -fsS https://tools.veracode.com/veracode-cli/install | sh
      ./veracode package --source $(Build.SourcesDirectory) --output $(Build.ArtifactStagingDirectory)/artifacts --trust
  
  env: 
      VERACODE_API_KEY_ID: 'f53289447dc774d0ef0987a3ee1545ea'
      VERACODE_API_KEY_SECRET: '2d19d36158beb63d5f7305ac9078b07c08013cc408036b2dffd52049d0a3998eb9ca329c2e0cc3b2235b5e2e822834bf8233e44c58404f63b5701a68e8b9f53f'


# Step 2: Archive Packaged Binaries
- task: ArchiveFiles@2
  displayName: Archive Packaged Binaries
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/artifacts'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

# Step 3: Publish the Archived File
- task: PublishBuildArtifacts@1
  displayName: Publish Packaged Binaries
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'packaged-binaries'
    publishLocation: 'Container'

# Step 4: Download the Archived File
- task: DownloadPipelineArtifact@2
  displayName: Download Packaged Binaries
  inputs:
    buildType: 'current'
    artifact: 'packaged-binaries'
    path: '$(Pipeline.Workspace)'

- task: VeracodePipelineScan@0
  inputs:
    authenticationMethod: 'UsernamePassword'
    fileToScan: '$(Pipeline.Workspace)/$(Build.BuildId).zip'
    policyName: 'test policy'
    breakPipeline: true



# Step 5: Scan the ZIP File with Veracode
# - task: CmdLine@2
#   displayName: Veracode Pipeline Scan
#   inputs:
#     script: |
#       curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
#       unzip -o pipeline-scan-LATEST.zip
#       java -jar pipeline-scan.jar -vid 'f53289447dc774d0ef0987a3ee1545ea' -vkey '2d19d36158beb63d5f7305ac9078b07c08013cc408036b2dffd52049d0a3998eb9ca329c2e0cc3b2235b5e2e822834bf8233e44c58404f63b5701a68e8b9f53f' -f $(Pipeline.Workspace)/$(Build.BuildId).zip